//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table1
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Second_name { get; set; }
    }
}
